# Generated by Django 2.0.5 on 2018-05-28 18:53

import core.models.session
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=12)),
                ('value', models.CharField(blank=True, max_length=32)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.Ballot')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=16, unique=True)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('-', 'Not started'), ('>', 'Started'), ('|', 'Paused'), ('=', 'Ended')], default='-', max_length=1)),
                ('start_time', models.DateTimeField(default=None, null=True)),
                ('end_time', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(regex='[A-Z]\\d{2}[0-9A-Z]\\d{5}')])),
                ('is_allowed', models.BooleanField(default=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electors', to='core.Ballot')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=9, validators=[django.core.validators.RegexValidator(regex='[A-Z]\\d{2}[0-9A-Z]\\d{5}')])),
                ('revision', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('0', 'Created'), ('1', 'Authenticated'), ('2', 'Authorized'), ('3', 'Voting'), ('9', 'Voted'), ('X', 'Not authenticated'), ('Y', 'Not verified'), ('Z', 'Canceled'), ('Q', 'Aborted'), ('N', 'Banned')], default='0', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('auth_code', models.CharField(blank=True, max_length=256)),
                ('key', models.CharField(default=core.models.session.generate_session_key, max_length=8)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Election')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.Station'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Election'),
        ),
    ]
