# Generated by Django 2.0.5 on 2018-05-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ballots',
            field=models.ManyToManyField(to='core.Ballot'),
        ),
    ]
