# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-21 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_load_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='kind',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
